2025-10-29 00:19:52,483 INFO    MainThread:81956 [wandb_init.py:setup_run_log_directory():705] Logging user logs to c:\Users\Gamer\Downloads\Python\ALFA UROP\wandb\run-20251029_001952-53tldn9d\logs\debug.log
2025-10-29 00:19:52,484 INFO    MainThread:81956 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to c:\Users\Gamer\Downloads\Python\ALFA UROP\wandb\run-20251029_001952-53tldn9d\logs\debug-internal.log
2025-10-29 00:19:52,485 INFO    MainThread:81956 [wandb_init.py:monkeypatch_ipython():624] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000014E4F3958E0>
2025-10-29 00:19:52,485 INFO    MainThread:81956 [wandb_init.py:init():832] calling init triggers
2025-10-29 00:19:52,486 INFO    MainThread:81956 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-10-29 00:19:55,622 INFO    MainThread:81956 [wandb_init.py:init():880] starting backend
2025-10-29 00:19:55,622 INFO    MainThread:81956 [wandb_init.py:init():883] sending inform_init request
2025-10-29 00:19:55,630 INFO    MainThread:81956 [wandb_init.py:init():891] backend started and connected
2025-10-29 00:19:55,681 INFO    MainThread:81956 [wandb_run.py:_label_probe_notebook():1330] probe notebook
2025-10-29 00:19:55,715 INFO    MainThread:81956 [wandb_init.py:init():961] updated telemetry
2025-10-29 00:19:55,855 INFO    MainThread:81956 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-29 00:19:56,180 INFO    MainThread:81956 [wandb_init.py:init():1036] starting run threads in backend
2025-10-29 00:20:01,846 INFO    MainThread:81956 [wandb_run.py:_console_start():2509] atexit reg
2025-10-29 00:20:01,847 INFO    MainThread:81956 [wandb_run.py:_redirect():2357] redirect: wrap_raw
2025-10-29 00:20:01,847 INFO    MainThread:81956 [wandb_run.py:_redirect():2426] Wrapping output streams.
2025-10-29 00:20:01,847 INFO    MainThread:81956 [wandb_run.py:_redirect():2449] Redirects installed.
2025-10-29 00:20:01,858 INFO    MainThread:81956 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-29 00:55:26,451 INFO    MainThread:81956 [wandb_init.py:_post_run_cell_hook():594] [no run ID] resuming backend
2025-10-29 01:33:37,604 INFO    MainThread:81956 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-10-29 01:33:37,613 INFO    MainThread:81956 [wandb_init.py:_pre_run_cell_hook():583] [no run ID] pausing backend
2025-10-29 01:33:37,667 INFO    MainThread:81956 [wandb_init.py:_post_run_cell_hook():594] [no run ID] resuming backend
2025-10-29 01:33:37,735 INFO    MainThread:81956 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-10-29 01:33:37,735 INFO    MainThread:81956 [wandb_init.py:_pre_run_cell_hook():583] [no run ID] pausing backend
2025-10-29 01:33:44,867 INFO    MainThread:81956 [wandb_run.py:_finish():2275] finishing run joneba-massachusetts-institute-of-technology/ALFA UROP/53tldn9d
2025-10-29 01:33:44,874 INFO    MainThread:81956 [jupyter.py:save_ipynb():404] not saving jupyter notebook
2025-10-29 01:33:44,875 INFO    MainThread:81956 [wandb_init.py:_jupyter_teardown():609] cleaning up jupyter logic
2025-10-29 01:33:44,875 INFO    MainThread:81956 [wandb_run.py:_atexit_cleanup():2474] got exitcode: 0
2025-10-29 01:33:44,877 INFO    MainThread:81956 [wandb_run.py:_restore():2456] restore
2025-10-29 01:33:44,877 INFO    MainThread:81956 [wandb_run.py:_restore():2462] restore done
2025-10-29 01:33:45,606 INFO    MainThread:81956 [wandb_run.py:_footer_sync_info():3872] logging synced files
